telegram:
  bot:
    token: "токен"
    username: "имя_бота"

auth:
  service:
    url: "http://localhost:8081"

steam:
  service:
    url: "http://localhost:8082"

openrouter:
  api:
    key: "sk-or-v1-your-openrouter-key" # Твой ключ OpenRouter
    url: "https://openrouter.ai/api/v1/chat/completions"
    model: "deepseek/deepseek-chat" # Или "google/gemini-2.0-flash-001"
