telegram:
  bot:
    token: "твой_токен"
    username: "имя_бота"

auth:
  service:
    url: "http://localhost:8081"

steam:
  service:
    url: "http://localhost:8082"

deepseek:
  api:
    key: "sk-your-deepseek-api-key" # Получи на platform.deepseek.com
    url: "https://api.deepseek.com/v1/chat/completions"
